query RepoFiles($owner: String!, $name: String!, $expression: String!) {
	repository(owner: $owner, name: $name) {
		refs(refPrefix: "refs/heads/", first: 100) {
			nodes {
				name
			}
		}
		defaultBranchRef {
			name
		}
		stargazers(first: 100) {
			nodes {
				login
			}
		}
		object(expression: $expression) {
			... on Tree {
				entries {
					name
					type
					mode
					language {
						name
					}
				}
			}
		}
	}
}
