query RepoInfo($owner: String!, $name: String!, $expression: String!) {
	repository(owner: $owner, name: $name) {
		id
		refs(refPrefix: "refs/heads/", first: 100) {
			nodes {
				name
			}
		}
		defaultBranchRef {
			name
			target {
				... on Commit {
					oid
					message
					committedDate
					status {
						state
					}
					history(first: 1) {
						totalCount
					}
				}
			}
		}
		stargazers(first: 100) {
			nodes {
				login
			}
		}
		object(expression: $expression) {
			... on Tree {
				entries {
					name
					type
					mode
					language {
						name
					}
				}
			}
		}
	}
}
