query repositories(
	$limit: Int!
	$privacy: RepositoryPrivacy
	$sort: RepositoryOrderField!
) {
	viewer {
		repositories(
			privacy: $privacy
			first: $limit
			orderBy: { field: $sort, direction: DESC }
		) {
			totalCount
			pageInfo {
				hasNextPage
			}
			nodes {
				id
				name
				owner {
					login
				}
				updatedAt
				description
				primaryLanguage {
					color
					name
				}
				forks {
					totalCount
				}
				stargazers {
					totalCount
				}
			}
		}
	}
}
